baseurl = "https://ayoubimaya.github.io/"
title = "Maya's Notes"
author = "David Hamp-Gonsalves"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle = "bw"
pygmentscodefences = true

[params]
  sitename = "Maya's Notes"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://ayoubimaya.github.io/post/about"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/ayoubimaya"
[[menu.main]]
    name = "LinkedIn"
    url  = "https://www.linkedin.com/in/mayaayoubi/"

[markup]
  defaultMarkdownHandler = "blackfriday"

